ARG PLONE_VERSION=6.1.0

FROM plone/plone-backend:${PLONE_VERSION}
ARG PLONE_VERSION
ENV PLONE_VERSION=${PLONE_VERSION}

# Add local code
COPY --chown=500:500 buildout.cfg /app/
COPY --chown=500:500 setup.py /app/
COPY --chown=500:500 src /app/src
ADD --chown=500:500 https://dist.plone.org/release/${PLONE_VERSION}/requirements.txt .

USER plone
# Install local requirements and fix permissions
RUN ./bin/pip install -r requirements.txt

ENTRYPOINT [ "/app/docker-entrypoint.sh" ]
CMD ["start"]